### ISSUE TITLE
Inconsistency in handling of files.

### ISSUE THREAD

**Issue by Brobin** [hephaest0s/usbkill#11]
I noticed a lot of inconsistency in handling of files, especially the log files.

When writing the log files, why are you using `os.system(echo '' >> logfile)` instead of using python's file writing?

```python
with open(logfile, 'a') as log:
    log.write(message)
```

It might also be a good idea to use context managers when dealing with files in python.

```python
# this is generally frowned upon
f = open(filename, 'w')
f.write("some text here")
f.close()

# the context manager is a better way to handle files
with open(filename, 'w') as f:
    f.write("some text here")
```

I would be willing to submit a pull request with some fixes if you are interested.

**Comment by hephaest0s** [comment]
Yes, you're absolutely right. This is one of the things I planned on improving.

If you would like to implement this, then please use context managers in settings_template(), load_settings() and log()

Thanks!
