### ISSUE TITLE
Update the title

### ISSUE THREAD

**Issue by pwnsdx** [hephaest0s/usbkill#21]
Hi there,

Here's the original title (actually the headline of the repo):

> usbkill waits for a change on your USB ports, then immediately kills your computer. Anti forensic, USB -> kill)

This short description seem to confuse people as I saw on Twitter **"USBKill used to wipe clean criminal’s PCs"**. This is **totally wrong**. It is does not wipe anything (and is not specially for criminals but that's not the subject).

Now here's the current README title:

> « usbkill » is an anti-forensic kill-switch that waits for a change on your USB ports and then immediately shuts down your computer.

It looks more comprehensible and will confuse less people.

So could you update the repo headline by the README one please?

Sincerely,
S.

**Comment by hephaest0s** [comment]
Yes, I did notice some articles by people that really have no idea what the script does. Luckily some articles are better. Very strange how this got hyped.

I will change the repo title.

**Comment by pwnsdx** [comment]
Thanks :)
