### ISSUE TITLE
OS X lsusb alternative

### ISSUE THREAD

**Issue by iamgyz** [hephaest0s/usbkill#23]
For OS X, why not use command
`system_profiler SPUSBDataType`
to check the usb status?
So that OS X users do not need to install lsusb anymore.

**Comment by hephaest0s** [comment]
I am developing this for linux and bsd systems. If someone would like to implement this feature for OSX then I will consider a pull request.

**Comment by pwnsdx** [comment]
Nice idea. I will look into it but as I'm not a Python expert I may not be able to do this. The function to modify would be https://github.com/hephaest0s/usbkill/blob/master/usbkill.py#L61

**Comment by pwnsdx** [comment]
Now implemented: https://github.com/hephaest0s/usbkill/commit/816fc98778ae6c17740507ea09ffd1a9c3ab7cf9

Thanks @iamgyz !

**Comment by iamgyz** [comment]
Thank you @pwnsdx 

Nice Job!

**Comment by pwnsdx** [comment]
Thanks, but the code I sent is now outdated, I made a pull request where I refactor the logic to fix a vulnerability: https://github.com/pwnsdx/usbkill/commit/7f57a0cb85931fc4d5b3a2d6fbcd6001e7b697d0
