### ISSUE TITLE
Version / Publish to Pip

### ISSUE THREAD

**Issue by Miserlou** [hephaest0s/usbkill#38]
Hey heph - awesome tool. Simple but effective!

Since there's already been some discussion of vulnerabilities and patches, I think it'd be good if this software included some internal semantic versioning so that it's easier to discuss which versions contain vulnerabilities.

As a bonus, you could include a setup.py file for versioning, and then distribute usbkill on [pip](http://the-hitchhikers-guide-to-packaging.readthedocs.org/en/latest/introduction.html) for easy installation.

Thanks again!

**Comment by pwnsdx** [comment]
Hello @Miserlou, thanks you for reporting this issue!

For the moment, usbkill have no vulnerabilities issues but @hephaest0s, @evilsocket and I are working on a possible one which does not come from usbkill but the lsusb. There may have other attack vectors such as Thunderbolt, Firewire etc. which could be added in the future.

I agree that a versioning and sending usbkill on pip is better and I can only encourage @hephaest0s to do so.

**Comment by pwnsdx** [comment]
https://github.com/hephaest0s/usbkill/issues/39

**Comment by hephaest0s** [comment]
This would be interesting when usbkill comes near a stable release but for now I expect a lot of development/changes for usbkill. So not yet.
