### ISSUE TITLE
Custom Commands In Configuration

### ISSUE THREAD

**Issue by Miserlou** [hephaest0s/usbkill#40]
This is a really easy one to do, but figured I'd make a ticket so we don't forget. 

Some people are already doing some [interesting things](https://github.com/JayMaree/usbkill/commit/01c643c94fdd0b8bf09dcb5e183e0c175e38649a) in this direction, might as well standardize it. The docs could even suggest some configurations for useful extensions (ex., take a picture, POST to a dead-man's switch on a remote server, rm -rf ~/.secret/, launch the nukes, etc.)

**Comment by pwnsdx** [comment]
Remember that custom commands like taking a picture **takes time**. usbkill must shutdown the computer in the most quickly way.

**Comment by Miserlou** [comment]
Yeah, that's true, but I think it's okay though, it should be up to the user. It doesn't take long to delete a file or send a POST.

(Part of me wants to add a --test mode with a profiler, or even better configurable safety margins so that if the commands take longer than, say, 2 seconds, it shuts down anyway.. but that's probably overkill at this point.)

**Comment by hephaest0s** [comment]
Addressed in https://github.com/hephaest0s/usbkill/commit/255b2f6ae09a58045938c522508d919b5bce4d3d
