### ISSUE TITLE
Replace custom settings file format with ConfigParser

### ISSUE THREAD

**Issue by Miserlou** [hephaest0s/usbkill#42]
The current settings file format is a bit hacky, it would be cleaner to replace it with the [standard python ConfigParser package](https://wiki.python.org/moin/ConfigParserExamples).

**Comment by pwnsdx** [comment]
Hello, thanks you for reporting this issue!

A pull request that contain config parser is waiting: https://github.com/blaa/usbkill/commit/d9934d7af44d8fce42f009edc875a7a1d47d52ed

**Comment by Miserlou** [comment]
Oh, good!

Another suggestion would be to use [clint](https://github.com/kennethreitz/clint), which could replace both the configparser and the argparser, with the added benefit of OS-specific config paths and terminal colors.. but I guess we haven't decided on if we're going to be a real python project that uses pip or if we're just another little script yet. :)

**Comment by pwnsdx** [comment]
Nice idea and yes you are right but there is more urgent like fixing the spoofing Product/VendorID vulnerability ( https://github.com/hephaest0s/usbkill/issues/36#ref-pullrequest-74262610 - https://github.com/hephaest0s/usbkill/pull/43 )

**Comment by Miserlou** [comment]
For sure. I'd like to become a contributor to this project, I think it is important work, and if we do it properly it might end up being useful to some of the paranoid distros like TAILS as well.

Can we merge blaa@d9934d7 , then get some versioning in place, so that I can fork from 0.1.0 and add the test mode as well as some other improvements? 

Do you work with heph, can you poke them? Or, alternately, can we reorganize so that usbkill is a group/organization that we're all able to contribute to? I just don't want to duplicate efforts and make ugly merges for people.

**Comment by pwnsdx** [comment]
> Can we merge [...], then get some versioning in place, so that I can fork from 0.1.0 and add the test mode as well as some other improvements?

There is a lot of things to fix in https://github.com/blaa/usbkill/commit/d9934d7af44d8fce42f009edc875a7a1d47d52ed as the job was done on an older version of usbkill so I'll let @hephaest0s talk about this.

> Do you work with heph, can you poke them?

I think I work with him due to my high number of commit but I'm not sure. You can poke/contact him by e-mail: https://github.com/hephaest0s/usbkill#contact

> Or, alternately, can we reorganize so that usbkill is a group/organization that we're all able to contribute to? I just don't want to duplicate efforts and make ugly merges for people.

Anyone can do a pull request for this and I think it's better that @hephaest0s (the owner) manage this.

**Comment by hephaest0s** [comment]
Addressed in https://github.com/hephaest0s/usbkill/commit/255b2f6ae09a58045938c522508d919b5bce4d3d
