### ISSUE TITLE
Remove Python3/Brew instructions for OSX users from docs

### ISSUE THREAD

**Issue by Miserlou** [hephaest0s/usbkill#44]
I think the only thing '3' about this is the use of print() rather than print - but print() still works in python2.6+, which is what ships with OSX. I think this can be removed from the docs now that lsusb is gone.

**Comment by pwnsdx** [comment]
You're right! I added it in my pull request: https://github.com/hephaest0s/usbkill/pull/43

**Comment by hephaest0s** [comment]
Fix by pwnsdx accepted.
