### ISSUE TITLE
Cold-Boot attack possible

### ISSUE THREAD

**Issue by pwnsdx** [hephaest0s/usbkill#45]
Hi there,

While usbkill shutdown quickly the computer, it is still possible to recover encryption keys when the computer is turned off by using CBA.

-> https://twitter.com/mariolinic/status/596395899112300545
-> https://www.youtube.com/watch?v=JDaicPIgn9U

I'm investigating in having a way to remove keys in the RAM before the computer shutdown (on all OS). If anyone have an idea about how it could be done or have another idea to prevent this kind of attack, you are welcome to tell me how :smiley:

**Comment by Zaxscdvf** [comment]
RAM wipe at shutdown should fix this.

**Comment by pwnsdx** [comment]
yes, but how I do this?

**Comment by pwnsdx** [comment]
I find something interesting for TrueCrypt (Linux): `truecrypt /wipecache`

**Comment by Zaxscdvf** [comment]
I don't think you could do this with this script as RAM wiping would be done by the kernel or in some cases BIOS could help as well. I say just leave a warning to the user that a cold boot attack is possible but can be fixed with a modified kernel or OS like tails which prevents such attacks. 

https://tails.boum.org/contribute/design/memory_erasure/
https://superuser.com/questions/464297/wipe-ram-on-shut-down-to-prevent-cold-boot-attack

**Comment by pwnsdx** [comment]
I've setup the warning here: https://github.com/pwnsdx/usbkill/commit/0194a6c9515bd45098ac7a86124e352d2f24782f

**Comment by fnatalucci** [comment]
Tails have a simple process that start at shutdown to wipe ram.

**Comment by terrorbyte** [comment]
Shouldn't the prevention of cold boot attacks be handled by the kernel or the FDE solution, not a tool to handle USB events? A warning really is the most you should do.

**Comment by Zaxscdvf** [comment]
@terrorbyte ya that's what we did.

**Comment by hephaest0s** [comment]
What @terrorbyte writes would be nice, but it might not work depending on how abrupt we crash the system.

If there is a command line tool we can call that would be nice. But, actually I want this issue to be solved in combination with another issue, the possibility to add custom command.

Depending on the setup you might want to delete private keys or release some encryption keys in a 'correct' way where the encryption program overwrites the ram it controls. This would also be a lot faster than just overwriting all ram and swap. I'd like overwriting all ram to be a sensible default that pre-populates the custom commands.
