### ISSUE TITLE
Adding a curses interface

### ISSUE THREAD

**Issue by Charlesleonius** [hephaest0s/usbkill#46]
I have been playing around with a curses interface and I think it looks nice. It may not be necessary but it's a nice touch. 
![screen shot 2015-05-08 at 3 40 04 pm](https://cloud.githubusercontent.com/assets/8421431/7546908/8b67fc14-f598-11e4-9e07-4ee1a4ab488c.png)

**Comment by Zaxscdvf** [comment]
looks pretty good!

**Comment by Charlesleonius** [comment]
Thanks, I made it so that selecting the Edit Settings option opens the configuration with nano for editing but it still needs some work.

**Comment by pwnsdx** [comment]
Looks great!

**Comment by hephaest0s** [comment]
It looks nice but I'd like to focus on the functionality before considering a curses interface. Keep a watch on the repo!

**Comment by Charlesleonius** [comment]
I will work on adding other functionalities and fixes but I have an interface for when you're ready. I think it would be nice to include everything in the script such as an option to query for connected devices and editing the configuration so nothing has to be done outside the script.
