### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ajkblue** [hephaest0s/usbkill#53]
I've been trying to run this script, but I continued to get this error:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 32, in <module>
    import configparser
ImportError: No module named configparser
```
So then I changed configparser to ConfigParser and it runs a bit further, albeit with this error:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 275, in <module>
    settings = startup_checks()
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 242, in startup_checks
    if subprocess.check_output("fdesetup isactive", shell=True).strip() != "true":
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'fdesetup isactive' returned non-zero exit status 1
```
I am aware that I don't have FileVault enabled, but I should still be able to run the script anyway, right? According to ```python -V``` I have version 2.6.7.

**Comment by pwnsdx** [comment]
Hello! Thanks you for reporting this issue.

Which version of OS X are you running on?

**Comment by ajkblue** [comment]
I'm a AppleSeed beta tester on 10.10.4. Could that be the problem?

**Comment by pwnsdx** [comment]
Thanks you for replying.

> I'm a AppleSeed beta tester on 10.10.4. Could that be the problem?

No, it normally should work. Could you type "fdesetup isactive" in the Terminal and give me the output please?

S.

**Comment by ajkblue** [comment]
```
Secure-MBA:~ austink$ fdesetup isactive
false
```

**Comment by pwnsdx** [comment]
Thanks. I'm working on a fix.

**Comment by pwnsdx** [comment]
Thanks.

@ajkblue: Is it doing everytime?

I'm working on a fix.

**Comment by pwnsdx** [comment]
@ajkblue: Could you try my fork and tell me if usbkill is still crashing please?
https://github.com/pwnsdx/usbkill

**Comment by ajkblue** [comment]
I've tried downloading from your fork and running, but am still running into the same issues. Again, I had to change the line ```import configparser``` to ```import ConfigParser``` to get it to even show the USBKILL Ascii art, or else I still would get this:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 32, in <module>
    import configparser
ImportError: No module named configparser
```
After changing the code to ```import ConfigParser```, running it still produces this:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 390, in <module>
    settings = startup_checks()
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 355, in startup_checks
    if subprocess.check_output("/usr/bin/fdesetup isactive", shell=True).strip() != "true":
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '/usr/bin/fdesetup isactive' returned non-zero exit status 1
```

**Comment by pwnsdx** [comment]
I think I found the problem. Can you update and try again please?

**Comment by ajkblue** [comment]
OK, tried again and got this after again changing ```import configparser``` to ```import ConfigParser```:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 390, in <module>
    settings = startup_checks()
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 355, in startup_checks
    if subprocess.check_output(["/usr/bin/fdesetup", "isactive"]).decode('utf-8').strip() != "true":
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/fdesetup', 'isactive']' returned non-zero exit status 1
```

**Comment by pwnsdx** [comment]
I fixed the configparser bug, the fix is waiting in the pull request and about Filevault, `['/usr/bin/fdesetup', 'isactive']` should works + I can't reproduce the issue…

**Comment by ajkblue** [comment]
Yup, configparser bug is fixed, but I still get the FileVault check issue, I'm not sure why. Running ```/usr/bin/fdesetup isactive``` manually returns false, as expected since it is not enabled. Again, still returning:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
Password:
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 431, in <module>
    settings = startup_checks()
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 396, in startup_checks
    if subprocess.check_output(["/usr/bin/fdesetup", "isactive"]).decode('utf-8').strip() != "true":
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/fdesetup', 'isactive']' returned non-zero exit status 1
```
Is there any other info you need me to provide to help diagnose this issue?

**Comment by pwnsdx** [comment]
Yes, can you try again and print the output here please? (https://github.com/pwnsdx/usbkill/commit/a7b37285863bbe3d55834e4c094e518bef720897)

**Comment by ajkblue** [comment]
OK, here is what's retuned after updating:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

Command '['/usr/bin/fdesetup', 'isactive']' returned non-zero exit status 1
```

**Comment by pwnsdx** [comment]
and now?

**Comment by ajkblue** [comment]
It seems to be working now! I can now proceed with the set-up!
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py 
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

[NOTICE] FileVault is disabled. Sensitive data SHOULD be encrypted.

[ERROR] You have lost your settings file. Get a new copy of the settings.ini and place it in /etc/usbkill/ or in /Users/austink/

```

**Comment by pwnsdx** [comment]
I think this is fixed for good now. fdesetup return exit code 0 when FileVault is activated and 1 when it is not. I added a check with a basic try/except.

However, I recommend to activate FileVault on your "secure macbook air" ;)

As it is resolved, you can close this issue :)

**Comment by ajkblue** [comment]
Yeah, quite a contradiction when it's named "Secure-MBA" even though it's not quite as secure that it could be :) Also, checking the settings.ini file tells me to run lsusb to get trusted usbid's for my computer, even though it is not required for the Mac. I am aware that running ```system_profiler SPUSBDataType``` will allow me to get those, but you may want to update the notice in settings.ini file and the main usbkill.py file at ```help_message``` to reflect that. Anyway, thanks!

**Comment by ajkblue** [comment]
Oh and their seems to be an issue as I have placed my settings.ini file with the correct USB ID's into the whitelist in ```/private/etc/usbkill/``` but the program still states ```[ERROR] You have lost your settings file. Get a new copy of the settings.ini and place it in /etc/usbkill/ or in /Users/austink/``` Maybe their isn't a correct symlink from ```/etc/``` to ```/private/etc```?

**Comment by pwnsdx** [comment]
Did you done `sudo ls /etc/usbkill/`? Is settings.ini correctly owned by root?

**Comment by ajkblue** [comment]
Yup, ```sudo ls /etc/usbkill/``` returns ```settings.ini```, and it is owned by root:
```
Secure-MBA:~ austink$ ls -lL /private/etc/usbkill/settings.ini 
-rwxr-xr-x  1 root  wheel  1712 May  9 15:49 /private/etc/usbkill/settings.ini
```

**Comment by pwnsdx** [comment]
hm, strange. I am working on it.

PS: I updated the settings.ini instructions, it has been added to the pull request.

**Comment by pwnsdx** [comment]
Did you tried `sudo stat /etc/usbkill/settings.ini`?

**Comment by ajkblue** [comment]
That returns:
```
Secure-MBA:~ austink$ sudo stat /etc/usbkill/settings.ini
16777220 14030343 -rwxr-xr-x 1 root wheel 0 1721 "May  9 16:02:55 2015" "May  9 16:02:48 2015" "May  9 16:02:48 2015" "May  9 14:20:30 2015" 4096 8 0 /etc/usbkill/settings.ini
```

**Comment by pwnsdx** [comment]
Can you try again (with my repo) please?

**Comment by ajkblue** [comment]
It still fails to read the settings.ini file from ```/etc/usbkill/```, returning:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

[NOTICE] FileVault is disabled. Sensitive data SHOULD be encrypted.

[ERROR] You have lost your settings file. Get a new copy of the settings.ini and place it in /etc/usbkill/ or in /Users/austink/Downloads/usbkill-master//

```
But when I copy the settings.ini file to ~/Downloads/usbkill-master/ folder, it returns:
```
Secure-MBA:~ austink$ sudo python /Users/austink/Downloads/usbkill-master/usbkill.py
             _     _     _ _ _  
            | |   | |   (_) | | 
  _   _  ___| |__ | |  _ _| | | 
 | | | |/___)  _ \| |_/ ) | | | 
 | |_| |___ | |_) )  _ (| | | | 
 |____/(___/|____/|_| \_)_|\_)_)

[NOTICE] FileVault is disabled. Sensitive data SHOULD be encrypted.
Traceback (most recent call last):
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 446, in <module>
    settings = startup_checks()
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 428, in startup_checks
    settings = load_settings(SETTINGS_FILE)
  File "/Users/austink/Downloads/usbkill-master/usbkill.py", line 291, in load_settings
    'whitelist': jsonloads(get_arg('whitelist')),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by pwnsdx** [comment]
Fixed: https://github.com/pwnsdx/usbkill/commit/f011eb0305fc6b915d37df3b05ad191adb30e778

**Comment by ajkblue** [comment]
Almost there! I cleared my ```settings.ini``` file in ```/etc/usbkill/``` and let the script re-create the file in that folder, which it did. I then edited the ```settings.ini``` and added my white-listed devices, and it would still work correctly, but if I add **--dev** to the script it is unable to find the settings.ini file in ```/etc/usbkill/```, as I copied it out of my Downloads folder, so if the ```settings.ini``` is in the same directory as the python script, in my case ```~/Downloads/usbkill-master/``` then **--dev will work**.

So the usbkill script **without --dev** works fine, and will kill my computer if I plug in a flash drive, **with --dev** it is unable to read ```/etc/usbkill/settings.ini```.

Sorry if that's a bit confusing.

**Comment by pwnsdx** [comment]
It should be fine now: https://github.com/pwnsdx/usbkill/commit/fb28832361fd5ec9fce65a62b8f8c89a5c030920

**Comment by ajkblue** [comment]
It works! Thanks for all of your help!

**Comment by pwnsdx** [comment]
Glad we fixed so many issues! Thanks you!

**Comment by hephaest0s** [comment]
I'm sorry these issues occurred. usbkill is still under active development!
