### ISSUE TITLE
What about melt_usbkill instead of remove_logs_and_settings

### ISSUE THREAD

**Issue by pwnsdx** [hephaest0s/usbkill#54]
Hi there,

I think it could be even better to remove (securely) the script itself (using \_\_file\_\_) + its directory (if it matches to the SHA1 signature of the repository) instead of just logs/settings so there will be no proof that usbkill has been used and you will have Plausible Deniability to say "Your USB device crashed my computer"

What do you think about this?

**Comment by hephaest0s** [comment]
Jup.

**Comment by pwnsdx** [comment]
@hephaest0s : Jup?

**Comment by hephaest0s** [comment]
I mean yes.

Except I don't think we need to match sha values, if we communicate what is happening well enough.

**Comment by pwnsdx** [comment]
Yes I have a better idea: if the directory name where the script is start with "usbkill" (e.g.: usbkill, usbkill-dev, usbkill-master…) then rename it and remove the content inside.

What do you think?

**Comment by Zaxscdvf** [comment]
@pwnsdx  what about just deleting the folder entirely? don't even rename it leave no trace.

**Comment by pwnsdx** [comment]
Hm sure we can but we will have to warn the user to not touch inside of the usbkill folder.

**Comment by hephaest0s** [comment]
implemented per https://github.com/hephaest0s/usbkill/commit/18c7784a59160f3b5c46f753aa7fc3e92d496e71 if the program folder starts with 'usb' then it will be deleted. Otherwise only usbkill.py is. Will add settings.ini in program folder shortly
