### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by scooter2015** [hephaest0s/usbkill#6]
Hello,

Here is what I tried, and the resulting message:

>sudo python3 ./usbkill.py 

Traceback (most recent call last):
  File "./usbkill.py", line 170, in <module>
    loop(whitelisted_devices, sleep_time)
  File "./usbkill.py", line 117, in loop
    log(msg)
  File "./usbkill.py", line 37, in log
    os.system("echo '" + str(time) + " " + msg + "' >> " + logfile)
TypeError: Can't convert 'tuple' object to str implicitly

**Comment by f03cuss** [comment]
I also got this error. I just commented out the line
os.system("echo '" + str(time) + " " + msg + "' >> " + logfile)
Was going to look at it later.

**Comment by hephaest0s** [comment]
Thanks!

**Comment by scooter2015** [comment]
On May 5, 2015 10:14:47 f03cuss wrote:
> I also got this error. I just commented out the line
> os.system("echo '" + str(time) + " " + msg + "' >> " + logfile)
> Was going to look at it later.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hephaest0s/usbkill/issues/6#issuecomment-99144764

Hello

Thanks for the super-quick reply. I commented out that line, and it works 
great now.

Thank you for creating this software!
-- 
Best Regards,

Richard Kut
~~~~~~~~~~~~~~~~
