### ISSUE TITLE
"Make sure to use (partial) disk encryption"?

### ISSUE THREAD

**Issue by pwnsdx** [hephaest0s/usbkill#72]
In the README:
> [!] Important: Make sure to use (partial) disk encryption! Otherwise they will get in anyway.

partial?

**Comment by Decagon** [comment]
I think they might be referring to Apple's FileVault 1, which just encrypts the home folder. However, it would be better to clarify what partial means in the readme.

**Comment by hephaest0s** [comment]
Indeed, not all systems feature full disk encryption by default. If I recall, e.g. Ubuntu only encrypts home folder out of the box, and Tails only encrypts the persistence folder. However, this is not necessarily bad as long as all information that is being protected resides in that folder.

**Comment by pwnsdx** [comment]
Hello,

The thing is that I feel that you are explicitely asking to use partial disk encryption. This is why I created this issue, it would be better to rephrase this.

**Comment by hephaest0s** [comment]
Addressed in latest commit.

**Comment by ghost** [comment]
Thanks you! :)
