### ISSUE TITLE
Downloaded a new copy to no avail

### ISSUE THREAD

**Issue by bet94** [hephaest0s/usbkill#87]
stuck at step 1:  

sudo python usbkill.py

[ERROR] You have lost your settings file. Get a new copy of the usbkill.ini and place it in /etc/ or in /Users/dgefe/Downloads/

I have redownloaded and placed usbkill.ini into downloads to no avail. 

Any help would be appreciated! 

Thanks

**Comment by jaxonashton** [comment]
So what was the solution on this? Closing the issue without providing a solution for others to learn from doesn't help anyone.
